"""empty message

Revision ID: 4e6e6b4cae0d
Revises: d5ed98688f73
Create Date: 2020-07-09 13:30:37.155119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e6e6b4cae0d'
down_revision = 'd5ed98688f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('abot_me', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'abot_me')
    # ### end Alembic commands ###
